import { describe, expect, it } from "vitest";
import { buildBulletinSuggestions } from "@/lib/bulletin/round-bulletin";
import type { RoundSummary } from "@/lib/competition/round-insights";

const summary: RoundSummary = {
  roundId: "GROUP_1",
  roundLabel: "Fase de grupos · Rodada 1",
  currentTime: "2026-06-16T08:00:00.000Z",
  matches: [
    {
      id: "m1",
      roundId: "GROUP_1",
      roundLabel: "Fase de grupos · Rodada 1",
      phaseLabel: "Grupo A · Rodada 1",
      matchNumber: 1,
      phase: "GROUP_STAGE",
      group: "A",
      groupRound: 1,
      kickoffAt: "2026-06-16T01:00:00.000Z",
      status: "FINISHED",
      scoringStatus: "CALCULATED",
      homeTeamId: "BRA",
      awayTeamId: "ARG",
      homeTeamName: "Brasil",
      awayTeamName: "Argentina",
      homeTeamIso2: "BR",
      awayTeamIso2: "AR",
      venue: null,
      homeScore: 2,
      awayScore: 1,
      resultCalculated: true,
      isVoid: false,
      revealed: true,
    },
    {
      id: "m2",
      roundId: "GROUP_1",
      roundLabel: "Fase de grupos · Rodada 1",
      phaseLabel: "Grupo B · Rodada 1",
      matchNumber: 2,
      phase: "GROUP_STAGE",
      group: "B",
      groupRound: 1,
      kickoffAt: "2026-06-16T03:00:00.000Z",
      status: "FINISHED",
      scoringStatus: "CALCULATED",
      homeTeamId: "ESP",
      awayTeamId: "FRA",
      homeTeamName: "Espanha",
      awayTeamName: "França",
      homeTeamIso2: "ES",
      awayTeamIso2: "FR",
      venue: null,
      homeScore: 0,
      awayScore: 0,
      resultCalculated: true,
      isVoid: false,
      revealed: true,
    },
  ],
  participants: [
    {
      participantId: "ana",
      displayName: "Ana",
      participantType: "HUMAN",
      avatarUrl: null,
      totalPoints: 19,
      totalBasePoints: 4,
      exactHits: 0,
      guessedMatches: 2,
      scoredMatches: 1,
      cells: [
        {
          matchId: "m1",
          guessText: "3 x 2",
          guesses: [{ guessId: "g1", matchId: "m1", participantId: "ana", slot: 1, homeScore: 3, awayScore: 2, administrativelyEntered: false }],
          points: 19,
          basePoints: 4,
          baseCode: "BASE_GOAL_DIFFERENCE",
          revealed: true,
          resultCalculated: true,
          isVoid: false,
          isOnlyScorer: true,
          isOnlyExact: false,
          isOnlyZero: false,
          audacityScore: 3.5,
        },
        {
          matchId: "m2",
          guessText: "1 x 0",
          guesses: [{ guessId: "g2", matchId: "m2", participantId: "ana", slot: 1, homeScore: 1, awayScore: 0, administrativelyEntered: false }],
          points: 0,
          basePoints: 0,
          baseCode: "BASE_MISS",
          revealed: true,
          resultCalculated: true,
          isVoid: false,
          isOnlyScorer: false,
          isOnlyExact: false,
          isOnlyZero: false,
          audacityScore: 1,
        },
      ],
      id: "ana",
    },
    {
      participantId: "bia",
      displayName: "Bia",
      participantType: "HUMAN",
      avatarUrl: null,
      totalPoints: 10,
      totalBasePoints: 10,
      exactHits: 1,
      guessedMatches: 2,
      scoredMatches: 1,
      cells: [
        {
          matchId: "m1",
          guessText: "0 x 1",
          guesses: [{ guessId: "g3", matchId: "m1", participantId: "bia", slot: 1, homeScore: 0, awayScore: 1, administrativelyEntered: false }],
          points: 0,
          basePoints: 0,
          baseCode: "BASE_MISS",
          revealed: true,
          resultCalculated: true,
          isVoid: false,
          isOnlyScorer: false,
          isOnlyExact: false,
          isOnlyZero: false,
          audacityScore: 0.5,
        },
        {
          matchId: "m2",
          guessText: "0 x 0",
          guesses: [{ guessId: "g4", matchId: "m2", participantId: "bia", slot: 1, homeScore: 0, awayScore: 0, administrativelyEntered: false }],
          points: 10,
          basePoints: 10,
          baseCode: "BASE_EXACT_SCORE",
          revealed: true,
          resultCalculated: true,
          isVoid: false,
          isOnlyScorer: false,
          isOnlyExact: true,
          isOnlyZero: false,
          audacityScore: 0,
        },
      ],
      id: "bia",
    },
    {
      participantId: "caio",
      displayName: "Caio",
      participantType: "BOT",
      avatarUrl: null,
      totalPoints: 0,
      totalBasePoints: 0,
      exactHits: 0,
      guessedMatches: 0,
      scoredMatches: 0,
      cells: [
        {
          matchId: "m1",
          guessText: "Sem palpite",
          guesses: [],
          points: 0,
          basePoints: 0,
          baseCode: "BASE_MISS",
          revealed: true,
          resultCalculated: true,
          isVoid: false,
          isOnlyScorer: false,
          isOnlyExact: false,
          isOnlyZero: false,
          audacityScore: null,
        },
        {
          matchId: "m2",
          guessText: "Sem palpite",
          guesses: [],
          points: 0,
          basePoints: 0,
          baseCode: "BASE_MISS",
          revealed: true,
          resultCalculated: true,
          isVoid: false,
          isOnlyScorer: false,
          isOnlyExact: false,
          isOnlyZero: true,
          audacityScore: null,
        },
      ],
      id: "caio",
    },
  ],
};

describe("round bulletin suggestions", () => {
  it("builds automatic highlights from the round summary", () => {
    const suggestions = buildBulletinSuggestions(summary);
    expect(suggestions.topScorers).toContain("Bia");
    expect(suggestions.topScorers).not.toContain("19 pontos");
    expect(suggestions.bestBet).toContain("Ana - Brasil 2 x 1 Argentina");
    expect(suggestions.honorableMention).toContain("Bia - Espanha 0 x 0 França");
    expect(suggestions.blunder).toContain("Caio");
    expect(suggestions.gauntlet).toContain("Nenhuma pedreira");
    expect(suggestions.highlights).toContain("participante(s) pontuaram");
    expect(suggestions.audacityAward).toContain("Ana");
  });
});
